razorpay.key.id=rzp_live_TLBGftRr6F3ORB
razorpay.key.secret=cn8APyDiC2sTGeSnxTWIdV2d
spring.data.mongodb.uri=mongodb://skillswapadmin:6i0YrkkMLJdFGUWr@ac-ggwambv-shard-00-00.oe4wprw.mongodb.net:27017,ac-ggwambv-shard-00-01.oe4wprw.mongodb.net:27017,ac-ggwambv-shard-00-02.oe4wprw.mongodb.net:27017/skillswap?ssl=true&replicaSet=atlas-116xta-shard-0&authSource=admin&appName=skillswap
